# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Build"

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
      
jobs:
  build:
    outputs:
      version: ${{ steps.vsix_version.outputs.version-number }}
    name: Build 
    runs-on: windows-2022
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0
      VSIX_PROJECT_ROOT: ./
      VSIX_OUTPUT_DIR: built
      
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET build dependencies
      uses: timheuer/bootstrap-dotnet@v1

    - name: Increment VSIX version
      id: vsix_version
      uses: timheuer/vsix-version-stamp@v1
      with:
        manifest-file: ${{ env.VSIX_PROJECT_ROOT }}\source.extension.vsixmanifest
        vsix-token-source-file: ${{ env.VSIX_PROJECT_ROOT }}\source.extension.cs

    - name: Restore
      run: nuget restore -Verbosity quiet

    - name: Build
      run: msbuild ${{ env.VSIX_PROJECT_ROOT }} /p:Configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m /p:OutDir=${{ env.VSIX_OUTPUT_DIR }}

    #- name: Test
    #  run: dotnet test path/to/test/project

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: InsertGuid.vsix
        path: ${{ env.VSIX_OUTPUT_DIR }}/**/*.vsix

  publish:
    needs: build  
    environment:
      name: release
      url: https://www.vsixgallery.com/extension/InsertGuid.c53fea6f-92c9-405f-b378-905869b5f2b3
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Download Package artifact
        uses: actions/download-artifact@v2
        with:
          name: InsertGuid.vsix

      - name: Upload to Open VSIX
        uses: timheuer/openvsixpublish@main
        with:
          vsix-file: InsertGuid.vsix
          readme: https://raw.githubusercontent.com/timheuer/vsix-devops-sample/main/readme.md

      - name: Tag and Release
        id: tag_release
        uses: softprops/action-gh-release@v0.1.13
        with:
          body: Release ${{ needs.build.outputs.version }}
          tag_name: ${{ needs.build.outputs.version }}
          files: |
            **/*.vsix
