# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "PR Build"

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
      
jobs:
  build:
    name: Build 
    runs-on: windows-2022
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0
      VSIX_PROJECT_ROOT: ./
      VSIX_OUTPUT_DIR: built
      
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET build dependencies
      uses: timheuer/bootstrap-dotnet@v1

    - name: Increment VSIX version
      id: vsix_version
      uses: timheuer/vsix-version-stamp@v1
      with:
        manifest-file: ${{ env.VSIX_PROJECT_ROOT }}\source.extension.vsixmanifest
        vsix-token-source-file: ${{ env.VSIX_PROJECT_ROOT }}\source.extension.cs

    - name: Restore
      run: nuget restore -Verbosity quiet

    - name: Build
      run: msbuild ${{ env.VSIX_PROJECT_ROOT }} /p:Configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m /p:OutDir=${{ env.VSIX_OUTPUT_DIR }}

    #- name: Test
    #  run: dotnet test path/to/test/project

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: InsertGuid.vsix
        path: ${{ env.VSIX_OUTPUT_DIR }}/**/*.vsix